deploymentName: grafana-deployment
deploymentLabel: grafana
replicaCount: 1
image:
  repository: grafana/grafana
  tag: latest
service:
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 30001